### ISSUE TITLE
Create proper topography for death valley

### ISSUE THREAD

**Issue by ybressler** [ybressler/dawn-of-man-mods#5]
Play around with various frequencies, see what shapes they produce:

**<noise_amplitudes values="0.5 0.165 0.1 0.05"/>**
Flat basin with huge mountains on the sides...

**<noise_amplitudes values="0.25 0.25 0.125 0.125"/>**
Flat basin with equally as huge mountains, width of the basin is less though...

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.05 0.05 0.05 0.025 0.025 0.125"/>**

Flat in the middle. Lots of tiny bumps on the sides...
![Screen Shot 2020-10-27 at 10 09 44 PM](https://user-images.githubusercontent.com/40807730/97382236-461c6780-18a1-11eb-9dd8-2975ecea152b.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.01 0.03 0.2 0.154 0.097 0.02 0.02 0.02"/>**
Default for "North"

![Screen Shot 2020-10-27 at 10 12 41 PM](https://user-images.githubusercontent.com/40807730/97382344-909de400-18a1-11eb-9216-e5eb469735e7.png)
![Screen Shot 2020-10-27 at 10 12 33 PM](https://user-images.githubusercontent.com/40807730/97382350-91cf1100-18a1-11eb-99d0-0ee5564a8749.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.01 0.06 0.2 0.154 0.097 0.02 0.02 0.02"/>**
_Changed one value from "default North"_
Better! More steep...

![Screen Shot 2020-10-27 at 10 12 41 PM](https://user-images.githubusercontent.com/40807730/97382754-74e70d80-18a2-11eb-91aa-2d99e035390c.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.06 0.2 0.154 0.097 0.02 0.02 0.02"/>**
Alter 1st parameter from previous. A lot less flat ground :)

![Screen Shot 2020-10-27 at 10 17 35 PM](https://user-images.githubusercontent.com/40807730/97382794-8d572800-18a2-11eb-850f-481b0abcdd9f.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.0147 0.06 0.2 0.154 0.1 0.02 0.02 0.02"/>**
_Added a new small wave between 1st and 2nd positions (of former)_

World is a lot crazier, but I enjoy the "close quarters"-ness of it!


![Screen Shot 2020-10-27 at 10 22 45 PM](https://user-images.githubusercontent.com/40807730/97383006-f9d22700-18a2-11eb-8d18-1f5ffbb5f08e.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.0147 0.007 0.06 0.2 0.154 0.1 0.02 0.02 0.02"/>**
_The world has become mountains..._

![Screen Shot 2020-10-27 at 10 31 11 PM](https://user-images.githubusercontent.com/40807730/97383504-2c305400-18a4-11eb-976d-15ac0ef3ccc3.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.0147 0.07 0.06 0.2 0.154 0.1 0.02 0.02 0.02"/>**
Mountains are slightly less steep...

Forces you to get creative when building defenses and farming. Yet, unsatisfying... 

![Screen Shot 2020-10-27 at 10 32 59 PM](https://user-images.githubusercontent.com/40807730/97383649-7b768480-18a4-11eb-9810-4971d2a51bd0.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.0147 0.07"/>**
The world is flat once again....

![Screen Shot 2020-10-27 at 10 35 40 PM](https://user-images.githubusercontent.com/40807730/97383811-d14b2c80-18a4-11eb-8c7b-5e18ccd21c19.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.0147 0.07 0.03 0.03 0.015"/>**
Still mostly flat 

![Screen Shot 2020-10-27 at 10 37 51 PM](https://user-images.githubusercontent.com/40807730/97383955-1bcca900-18a5-11eb-80d0-0e848a4d3935.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.1 0.0147 0.07 0.03 0.03 0.015 0.015 0.0075 0.015 0.0075"/>**
The teeniest tiniest hills...

![Screen Shot 2020-10-27 at 10 41 05 PM](https://user-images.githubusercontent.com/40807730/97384173-8f6eb600-18a5-11eb-902e-935d7b342fac.png)

**Comment by ybressler** [comment]
# Winner!
**<noise_amplitudes values="0.125 0.250 0.125 0.0625 0.03125 0.015"/>**
This one creates a massive central hill and several wide open valleys

![Screen Shot 2020-10-27 at 10 41 05 PM](https://user-images.githubusercontent.com/40807730/97384431-1328a280-18a6-11eb-86bf-4b69efda7a17.png)
![Screen Shot 2020-10-27 at 10 44 32 PM](https://user-images.githubusercontent.com/40807730/97384443-1754c000-18a6-11eb-86ed-a88f68dd3885.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.125 0.125 0.0625 0.03125 0.015"/>**
_Added an additional wavelength to previous_

Parts of the map are very steep. Others are very flat.

![Screen Shot 2020-10-27 at 10 46 51 PM](https://user-images.githubusercontent.com/40807730/97384589-5e42b580-18a6-11eb-8395-5a268775e283.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.115 0.105 0.0905 0.1333 0.001 0.025"/>**
_Crazy...._

![Screen Shot 2020-10-27 at 10 51 22 PM](https://user-images.githubusercontent.com/40807730/97384882-00fb3400-18a7-11eb-8e25-d0622ca0f074.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.115 0.105 0.0905 0.01333 0.001 0.025"/>**

Getting warmer...


![Screen Shot 2020-10-27 at 10 53 03 PM](https://user-images.githubusercontent.com/40807730/97385010-3869e080-18a7-11eb-8c71-f9efa7818a96.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.115 0.105 0.0905 0.111 0.001 0.025"/>**

Maybe too much now...

![Screen Shot 2020-10-27 at 10 55 39 PM](https://user-images.githubusercontent.com/40807730/97385186-91d20f80-18a7-11eb-9684-0f7b1f2ee7cb.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.115 0.105 0.0905 0.055 0.025 0.0001"/>**
This one is pretty cool...


![Screen Shot 2020-10-27 at 10 57 57 PM](https://user-images.githubusercontent.com/40807730/97385356-eaa1a800-18a7-11eb-97af-b3a95a3d2ed2.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.115 0.105 0.0905 0.055 0.0001"/>**
Good in some areas. Not great in others.

![Screen Shot 2020-10-27 at 11 01 01 PM](https://user-images.githubusercontent.com/40807730/97385602-613ea580-18a8-11eb-82c9-f137a3c31db2.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.250 0.115 0.0905 0.055 0.002 0.0001"/>**
Much too flat...

![Screen Shot 2020-10-27 at 11 02 49 PM](https://user-images.githubusercontent.com/40807730/97385684-95b26180-18a8-11eb-84bf-2800c7c69bba.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.500 0.150 0.105 0.02 0.0905 0.055 0.002 0.001"/>**
Everything is on the map edges now...


![Screen Shot 2020-10-27 at 11 04 57 PM](https://user-images.githubusercontent.com/40807730/97385796-e45ffb80-18a8-11eb-8225-714379ebc2f2.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.050 0.150 0.105 0.02 0.0905 0.055 0.002 0.001"/>**

Too flat still

**Comment by ybressler** [comment]
# WINNER
**<noise_amplitudes values="0.125 0.25 0.09 0.105 0.02 0.0905 0.02 0.002"/>**
Good amount of balance here!

![Screen Shot 2020-10-27 at 11 09 48 PM](https://user-images.githubusercontent.com/40807730/97386152-9c8da400-18a9-11eb-9987-657ce802ad1e.png)

**Comment by ybressler** [comment]
# WINNER
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.002"/>**
_Changed `0.09` (from previous) to `0.11`_

It's a winner too!

![Screen Shot 2020-10-27 at 11 12 04 PM](https://user-images.githubusercontent.com/40807730/97386269-d78fd780-18a9-11eb-9744-08ad5f95b35b.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.875 0.0905 0.02 0.002"/>**
_Increase value from `0.02` to `0.0875`_

Good pitch, but areas are a bit too steep...


![Screen Shot 2020-10-27 at 11 15 19 PM](https://user-images.githubusercontent.com/40807730/97386502-54bb4c80-18aa-11eb-82e9-05b230706402.png)

**Comment by ybressler** [comment]
# Winner!

**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.02 0.002"/>**
_Revert, but this time, add another 0.02 at 2nd to last position_


![Screen Shot 2020-10-27 at 11 17 15 PM](https://user-images.githubusercontent.com/40807730/97386639-a1068c80-18aa-11eb-967a-b20e7341be61.png)

**Comment by ybressler** [comment]
# Winner!
<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.01 0.002"/>
_Changed 2nd to last 0.02 to 0.01_

Nice rivervalley with BIG mountains...

![Screen Shot 2020-10-27 at 11 19 29 PM](https://user-images.githubusercontent.com/40807730/97386768-f347ad80-18aa-11eb-8694-702936f97cd5.png)

**Comment by ybressler** [comment]
# Winner!
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.03 0.02 0.01 0.002"/>**
Lush open plains broken by hills and mountains

![Screen Shot 2020-10-27 at 11 23 13 PM](https://user-images.githubusercontent.com/40807730/97386987-736e1300-18ab-11eb-9044-b3f0107c6110.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.02 0.01"/>**
Weird...

![Screen Shot 2020-10-27 at 11 28 08 PM](https://user-images.githubusercontent.com/40807730/97387433-5be35a00-18ac-11eb-952b-f314826cf593.png)

**Comment by ybressler** [comment]
# Winner
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.02 0.001"/>**

Solid choice with this one...

![Screen Shot 2020-10-27 at 11 29 15 PM](https://user-images.githubusercontent.com/40807730/97387389-43733f80-18ac-11eb-862a-e2026ce42628.png)

**Comment by ybressler** [comment]
# Good
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.001"/>**

![Screen Shot 2020-10-27 at 11 32 02 PM 1](https://user-images.githubusercontent.com/40807730/97387582-ae247b00-18ac-11eb-9315-eb389997f4f7.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.015 0.001"/>**
Much too open...


![Screen Shot 2020-10-27 at 11 33 34 PM](https://user-images.githubusercontent.com/40807730/97387693-e75ceb00-18ac-11eb-937f-39ba23553084.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.002"/>**

This one is good too


![Screen Shot 2020-10-27 at 11 35 18 PM](https://user-images.githubusercontent.com/40807730/97388051-a74a3800-18ad-11eb-81c5-b807ee0e87f6.png)

**Comment by ybressler** [comment]
# FINALLY!
**<noise_amplitudes values="0.125 0.25 0.11 0.105 0.02 0.0905 0.02 0.005 0.002"/>**

This is what I wanted!!!

![Screen Shot 2020-10-27 at 11 37 50 PM](https://user-images.githubusercontent.com/40807730/97388020-94376800-18ad-11eb-8c49-67fd977ebd44.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.2 0.2 0.1 0.2 0.1 0.2"/>**
Crazy mountains, just a few flat spots

![Screen Shot 2020-10-29 at 12 37 08 AM](https://user-images.githubusercontent.com/40807730/97526265-252a4400-197f-11eb-8b2a-5be0bb37345c.png)

**Comment by ybressler** [comment]
**<noise_amplitudes values="0.2 0.4 0.2 0.1"/>**
This one is pretty compelling...

![Screen Shot 2020-10-29 at 12 45 23 AM](https://user-images.githubusercontent.com/40807730/97526764-37f14880-1980-11eb-9f04-e4d75c1ad1bf.png)

**Comment by ybressler** [comment]
Valley basin:
_(I forgot the aplitudes)_

![Screen Shot 2020-10-29 at 1 26 57 AM](https://user-images.githubusercontent.com/40807730/97610514-5d676c00-19eb-11eb-8f27-59ba34ef1e3f.png)

**Comment by ybresslerTA** [comment]
These are crazy....
**<noise_amplitudes values="0.25 0.25 0.0555 0.15 0.1 0.02 0.045 0.02 0.1"/>**
![Screen Shot 2020-11-06 at 8 42 24 PM](https://user-images.githubusercontent.com/73961460/98428723-d3657600-2070-11eb-834a-fa2c48d81235.png)

**Comment by ybresslerTA** [comment]
**<noise_amplitudes values="0.25 0.25 0.25 0.125 0.125"/>**
Dumb and boring
![Screen Shot 2020-11-06 at 8 45 50 PM](https://user-images.githubusercontent.com/73961460/98428809-3eaf4800-2071-11eb-9f5d-d2d3606cc183.png)

**Comment by ybresslerTA** [comment]
**<noise_amplitudes values="0.25 0.125 0.125 0.0675 0.0675 0.1 0.01"/>**
![Screen Shot 2020-11-06 at 8 48 33 PM](https://user-images.githubusercontent.com/73961460/98428870-977ee080-2071-11eb-8641-18f589929cca.png)

**Comment by ybresslerTA** [comment]
**<noise_amplitudes values="0.25 0.0675 0.01 0.1 0.01"/>**
![Screen Shot 2020-11-06 at 8 51 02 PM](https://user-images.githubusercontent.com/73961460/98428945-d90f8b80-2071-11eb-8b89-a64fc1c53941.png)

**Comment by ybresslerTA** [comment]
**<noise_amplitudes values="0.25 0.0675 0.01 0.1 0.01 0.25"/>**
![Screen Shot 2020-11-06 at 8 53 11 PM](https://user-images.githubusercontent.com/73961460/98428999-2be94300-2072-11eb-9589-421561785bcc.png)

**Comment by ybresslerTA** [comment]
**<noise_amplitudes values="0.25 0.0675 0.2 0.1 0.05 0.01 0.1"/>**
![Screen Shot 2020-11-06 at 8 56 07 PM](https://user-images.githubusercontent.com/73961460/98429070-897d8f80-2072-11eb-9d23-daae5dc9e813.png)

**Comment by ybresslerTA** [comment]
# Winner!
**<noise_amplitudes values="0.01 0.06 0.25 0.01 0.15 0.097 0.02 0.02 0.02"/>**
![Screen Shot 2020-11-06 at 9 09 11 PM](https://user-images.githubusercontent.com/73961460/98429405-618f2b80-2074-11eb-9598-e32c99d35ed8.png)

**Comment by ybresslerTA** [comment]
# ANOTHER WINNER
**<noise_amplitudes values="0.01 0.06 0.25 0.01 0.10 0.097 0.02 0.02 0.02"/>**
![Screen Shot 2020-11-06 at 9 11 21 PM](https://user-images.githubusercontent.com/73961460/98429450-ae730200-2074-11eb-8bcd-58a3a5fb6d6b.png)

**Comment by ybresslerTA** [comment]
# THIS IS THE TOPOGRAPHY AND I'M STICKING WITH IT
**<noise_amplitudes values="0.01 0.06 0.25 0.05 0.115 0.097 0.05 0.03"/>**
![Screen Shot 2020-11-06 at 9 25 59 PM](https://user-images.githubusercontent.com/73961460/98429776-c5b2ef00-2076-11eb-9aef-2619d307e7ff.png)
